#spring:
#  main:
#    allow-bean-definition-overriding: true
#
#### Logger
#### ENV use to local
#logging:
#  level:
#    io.r2dbc.mysql.QUERY: DEBUG
#    io.r2dbc.mysql.PARAM: DEBUG
#    org:
#      springframework:
#        web: TRACE
#      springframework.r2dbc: TRACE
#      springframework.transaction: TRACE
#
#read:
#  datasource:
#    driver: mysql
#    host: localhost
#    port: 23306
#    database: default
#    username: root
#    password: 1234
#write:
#  datasource:
#    driver: mysql
#    host: localhost
#    port: 23306
#    database: default
#    username: root
#    password: 1234


#javax.persistence.jdbc.user


#javax.


#properties>
#            <!-- PostgreSQL -->
#            <property name="javax.persistence.jdbc.url"
#                      value="jdbc:postgresql://localhost:5432/blogdb"/>
#            <!-- Credentials -->
#            <property name="javax.persistence.jdbc.user"
#                      value="user"/>
#            <property name="javax.persistence.jdbc.password"
#                      value="password"/>
#            <!-- The Vert.x SQL Client connection pool size -->
#            <property name="hibernate.connection.pool_size"
#                      value="10"/>
#            <!-- Automatic schema export -->
#            <property name="javax.persistence.schema-generation.database.action"
#                      value="drop-and-create"/>
#            <!-- SQL statement logging -->
#            <property name="hibernate.show_sql" value="true"/>
#            <property name="hibernate.format_sql" value="true"/>
#            <property name="hibernate.highlight_sql" value="true"/>
#        </properties>




#javax.persistence.jdbc:
#  url: jdbc:mysql://localhost:3306/default
#  user: default
#  password: 1234

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/default
#    username: default
#    password: 1234


#logging:
#  level:
#    root: debug
